// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHRHOSqo2VxYDc2To4nf6Gydg2XGxtDyA',
    appId: '1:813199146802:web:fe6d61215b65dd22e1a12b',
    messagingSenderId: '813199146802',
    projectId: 'clg-chat-e0a95',
    authDomain: 'clg-chat-e0a95.firebaseapp.com',
    databaseURL: 'https://clg-chat-e0a95-default-rtdb.firebaseio.com',
    storageBucket: 'clg-chat-e0a95.firebasestorage.app',
    measurementId: 'G-BBT37SYDKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRH2YoTpUdXkVMqLQKVnpJXZAAkuS_fg8',
    appId: '1:813199146802:android:cf393a4e4d7e214ce1a12b',
    messagingSenderId: '813199146802',
    projectId: 'clg-chat-e0a95',
    databaseURL: 'https://clg-chat-e0a95-default-rtdb.firebaseio.com',
    storageBucket: 'clg-chat-e0a95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDed-q8Da4fM8FpSg8CAB_CAlzhKnSLig',
    appId: '1:813199146802:ios:0bcdeafd3a7a90a5e1a12b',
    messagingSenderId: '813199146802',
    projectId: 'clg-chat-e0a95',
    databaseURL: 'https://clg-chat-e0a95-default-rtdb.firebaseio.com',
    storageBucket: 'clg-chat-e0a95.firebasestorage.app',
    androidClientId: '813199146802-kfm8djj9u1hcf1t5np857tlni4mlq5nq.apps.googleusercontent.com',
    iosClientId: '813199146802-d3cqg9brrip0bm4nlc5r1vrt9ll4dicb.apps.googleusercontent.com',
    iosBundleId: 'com.example.clgChat',
  );

}